apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: demodb
  name: demodb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: demodb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: demodb
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: TODODemo
        - name: MYSQL_PASSWORD
          value: todoPassword
        - name: MYSQL_ROOT_PASSWORD
          value: todoPassword
        - name: MYSQL_USER
          value: todoUser
        image: mysql:latest
        imagePullPolicy: ""
        name: demodb
        ports:
        - containerPort: 3360
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: demodb-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: demodb-claim0
        persistentVolumeClaim:
          claimName: demodb-claim0
status: {}
